### ISSUE TITLE
Phantomjs executable needs to be in PATH

### ISSUE THREAD

**Issue by UltimateHackers** [shogunlab/shuriken#3]
```
root@kali:~/shuriken# python shuriken_xss.py -u http://dramaonline.pk/search.php?q={xss} -p wordlist.txt
Traceback (most recent call last):
  File "shuriken_xss.py", line 198, in <module>
    Shuriken().main()
  File "shuriken_xss.py", line 37, in __init__
    self.browser = Browser("phantomjs")
  File "/usr/local/lib/python2.7/dist-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH.
```

**Comment by UltimateHackers** [comment]
Oh sorry, its something that needs to be downloaded. My bad 👍 
Btw you should mention the requirements in your repo.

**Comment by shogunlab** [comment]
Hey! Thanks for flagging this up, I just merged a commit made by @paralax which addresses this issue. Now, you should be able to get all the dependencies via pip so it should be easier to get going with Shuriken. Hope you enjoy using the tool and please let me know if you have any additional ideas for improvements!

**Comment by UltimateHackers** [comment]
@shogunlab I have done everything your readme tells a user to do but shuriken is taking forever to scan.
Here's a short video I have made regarding the issue: http://shuriken.vidmeup.com/

**Comment by shogunlab** [comment]
I'll investigate the issue and see if there's anything I can add to improve the speed.

**Comment by s0md3v** [comment]
If you are getting this error, you need 'geckodriver'.

You can find how to get it by googling: 'install geckodriver on windows/linux/mac'.
